### ISSUE TITLE
Segmentation fault while execute using shared library not in static library on iMx28.

### ISSUE THREAD

**Issue by ganeshthorner** [Cirrus-Link/Sparkplug#12]
Hi,

Platform : iMx28 - cross compilation
I'm trying to use sparkplug library for example.c application.It is executing fine when compilation done by static library(libsparkplug_b.a). But same example.c is giving 'segmentation fault' when compilation done by shared(libsparkplug_b.so) library.

Please help me to find/fix the issue.

![image](https://user-images.githubusercontent.com/43740602/46274576-8cdeec80-c577-11e8-8be9-dbe7fb564362.png)

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
