### ISSUE TITLE
The C library message decoder does not properly decode messages from an Iginition instance

### ISSUE THREAD

**Issue by jeliser** [Cirrus-Link/Sparkplug#16]
Our software is C++, so I followed the instructions and example applications for the C application.  I was able to write a server and client that is able to publish and subscribe to messages and decoding on this loopback was correct.  When I pointed our client to the Ignition server, I was able to get the message, and the Cirrus C library "successfully" decoded it, but the data values were incorrect (all the values were 0.0000 (double) and not all the metric fields were decoded).  The decode method returned successful, but it was not.  We're using spBv1.0 and we tested with particular topics and the # all topic.

I went through a bunch of permutations and this is where I am:
```
Server Kelvin (C)      / Client Kelvin (C)                   -> SUCCESS
Server Kelvin (C)      / Client Cirrus-Link Example (Python) -> SUCCESS
Server Kelvin (C)      / MQTT.fx (JAVA)                      -> SUCCESS
Server Ignition (JAVA) / Client Kelvin (C)                   -> FAILED
Server Ignition (JAVA) / Client Cirrus-Link Example (C)      -> FAILED
Server Ignition (JAVA) / Client Cirrus-Link Example (Python) -> SUCCESS
Server Ignition (JAVA) / MQTT.fx (JAVA)                      -> SUCCESS
```

I believe connecting the C library to an Ignition server will reproduce the problem.

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
