### ISSUE TITLE
node-red-contrib-sparkplug not possible to send DDEATH

### ISSUE THREAD

**Issue by tord-v** [Cirrus-Link/Sparkplug#19]
After last years update when @mattmiller2112 updated the index.js, and added the "option" parameter.
I think this is why, node-red-contrib-sparkplug is not recieving DDEATH messages properly.

The direct result of that change is that devices cannot get individual DDEATH messages. Which i think is quite important when one Node can hold several devices. QOS data will be kept "Good" :(

Specifically:
node-red-contrib-sparkplug/sparkplug/sparkplug.js, calls **publishDeviceDeath**
`
else if (messageType === "DDEATH") {
                // Clear device cache
                delete deviceCache[deviceId];
                // Publish device data
                sparkplugClient.publishDeviceDeath(deviceId, payload);
`
which javascript/sparkplug-client/index.js expect the **option** parameter, which is not included.
`
// Publishes Device DEATH certificates for the edge node
    this.publishDeviceDeath = function(deviceId, payload, **options**) {
        var topic = version + "/" + groupId + "/DDEATH/" + edgeNode + "/" + deviceId;
        // Add seq number
        addSeqNumber(payload);
        // Publish
        logger.info("Publishing DDEATH for device " + deviceId);
        client.publish(topic, encodePayload(maybeCompressPayload(payload, options)));
        messageAlert("published", topic, payload);
`
Keep up the good work!

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
