### ISSUE TITLE
SparkplugRaspberryPiExample: clarification about the bdSeq 

### ISSUE THREAD

**Issue by sabrine2020** [Cirrus-Link/Sparkplug#3]
Hello,

I am reading this example:
[https://github.com/Cirrus-Link/Sparkplug/blob/master/sparkplug_b/raspberry_pi_examples/java/src/main/java/com/cirruslink/example/SparkplugRaspberryPiExample.java](url)

According to the Sparkplug B specification in the 16.1 section:

> A bdSeq number as a metric should be included in the payload. This should match the bdSeq number
> provided in the MQTT CONNECT packet’s LW&T payload. This allows backend applications to correlate
> NBIRTHs to NDEATHs. The bdSeq number should start at zero and increment by one on every new MQTT
> CONNECT

In the example if I well understood, the bdSeq  is not the same in the MQTT connect and the NBIRTH, I saw that it is incremented in publishBirth(). I don't understand why since it should match the one in the MQTT connect.

have I missed something?

Thanks and best regards,
Sabrina

**Comment by wes-johnson** [comment]
Sabrina,

This is a bug in the example.  The specification is correct.  We'll take a closer look and get the example fixed.

Regards,
Wes

**Comment by wes-johnson** [comment]
Fixed in https://github.com/Cirrus-Link/Sparkplug/commit/30c8a521237ad6e0d2e92e819fd80992b8d8b668.
