### ISSUE TITLE
Does the DDEATH message contains a payload or not?

### ISSUE THREAD

**Issue by sabrine2020** [Cirrus-Link/Sparkplug#4]
Hello,

I am a little bit confused about the DDEATH payload.
In the specification, section 16.7:
> The DDEATH message requires the following payload components.
> The DDEATH must include the a seq number in the payload and it must have a value of one greater than
> the previous MQTT message from the EoN node contained unless the previous MQTT message contained
> a value of 255. In this case the seq number must be 0.

And in section 17.8:
> The DDEATH does not include a payload.

Which is the correct one?

Thanks and best reagrds,
Sabrine

**Comment by wes-johnson** [comment]
Thanks.  In this case section 16.7 is correct.  We'll update the specification appropriately.

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
