### ISSUE TITLE
Specification parkplugB: clarification about the figure 4

### ISSUE THREAD

**Issue by sabrine2020** [Cirrus-Link/Sparkplug#5]
Hello,

In page 22, figure 4 (EoN node MQTT Session Establishment) of the Sparkplug specificationB:

- Message 2 is written SUBSCRIBE but it is PUBLISH, right?
- Message 3 is written PUBLISH but it is a SUBSCRIBE, right?
-  After the sent of the second NBIRTH, the state is ONLINE, right?
- The last message is PUBLISH NDATA, right?

Thanks and best regards,
Sabrine

**Comment by PaulFake** [comment]
I found this diagram confusing as well.  Can anyone provide some insight on this?

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
