### ISSUE TITLE
Memory leaks and other issues reported by valgrind

### ISSUE THREAD

**Issue by mm-ark** [Cirrus-Link/Sparkplug#7]
Hi folks!

Valgrind memory check reports memory leaks and other issues within the c client library.
Please check the attached results from valgrind and the example program.

Could you please fix the issues asap? We want implement support of Inductive Automation Ignition Platform, so would like avoid any problems within our project schedule...

Results screenshot:
![sparkplugmemoryleaksandotherissues2](https://user-images.githubusercontent.com/22474839/35627731-12a01db4-069a-11e8-8cad-d81642a9ed5b.png)

Example program
[SparkplugMemoryCheck2.zip](https://github.com/Cirrus-Link/Sparkplug/files/1681945/SparkplugMemoryCheck2.zip)

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
