### ISSUE TITLE
segmentation fault running example.c running on linux ARM9 platform

### ISSUE THREAD

**Issue by alef75** [Cirrus-Link/Sparkplug#9]
file example.c
function publish_node_birth()
```
fprintf(stdout, "Adding metric: 'Node Metric0'\n");
char nbirth_metric_zero_value[] = "hello node";
add_simple_metric(&nbirth_payload, "Node Metric0", true, Node_Metric0, METRIC_DATA_TYPE_STRING, false, false, false, &nbirth_metric_zero_value, sizeof(nbirth_metric_zero_value));
```
nbirth_metric_zero_value is a char pointer so no need to use it's address passing it the correct call shall be:
`add_simple_metric(&nbirth_payload, "Node Metric0", true, Node_Metric0, METRIC_DATA_TYPE_STRING, false, false, false, nbirth_metric_zero_value, sizeof(nbirth_metric_zero_value));`

Another issue regard the sparkplug_b client C library:
file sparkplug_b.c
the are improper use of the %zd specificator in print functions like:
```
else if (datatype == METRIC_DATA_TYPE_STRING || datatype == METRIC_DATA_TYPE_TEXT || datatype == METRIC_DATA_TYPE_UUID) {
		DEBUG_PRINT(("Setting datatype: %zd, with value: %s\n", datatype, (char *)value));
		...
```
This in particular make the example to crash with segmentation fault.
the %zd shall be used only printing size_t type.
in ARM9 size_t is 32 bit, but the above source try to print a 64 bit value.

**Comment by wes-johnson** [comment]
Repo moved to: https://github.com/eclipse/tahu/
